version: '3.9'

services:
  eureka:
    image: eureka
    ports:
      - "8761:8761"
  cloud-gateway:
    image: cloud-gateway
    ports:
      - "8080:8080"
  community:
    image: community
    ports:
      - "8081:8080"
  spring-server:
    image: media
    ports:
      - "8082:8080"
