version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306
    networks:
      - msa-network

  gateway:
    image: blackbeen99/gateway
    depends_on:
      - mysql
    ports:
      - 8080:8081
    networks:
      - msa-network

  eureka:
    image: blackbeen99/eureka
    depends_on:
      - config
      - registry
      - mysql
    ports:
      - 8761:8761
    networks:
      - msa-network

networks:
  msa-network:
    external: true